def menu():
    print('Select from the menu below:')
    print('L [INPUT]: prints all results from a directory')   
    print('L [INPUT] -f: prints files from a directory')
    print('L [INPUT] -s [INPUT]: prints file input from a directory')
    print('L [INPUT] -e [INPUT]: prints file input extension from a directory')
    print('L [INPUT] -r: prints from all directories and subdirectories')
    print('L [INPUT] -r -f: prints all files from all directories')
    print('L [INPUT] -r -s [INPUT]: prints file input from all directories')
    print('L [INPUT] -r -e [INPUT]: prints file input extension from all directories')
    print('C [INPUT] -n [INPUT]: creates file with a new profile inside and on server')
    print('D [INPUT]: deletes file in directory')
    print('R [INPUT]: prints all file contents')
    print('P [INPUT]: loads file contents and offers information')
    print('P [INPUT] -a: adds post to an existing profile')
    print('P [INPUT] -d: delete post from profile')
    print('P [INPUT] -g: prints all posts from profile')
    print('P [INPUT] -b: add or update bio of profile')
    print('P [INPUT] -u: update dsuserver, username, and/or password of profile')
    print('Supported shorcut keywords for post:')
    print('OpenWeather:')
    print('             @weather - description of weather')
    print('             @weather_description - description of weather')
    print('             @weather_temperature - temperature today')
    print('             @weather_high_temperature - highest temperature today')
    print('             @weather_low_temperature - lowest temperature today')
    print('             @weather_longitude - longitude of the weather location')
    print('             @weather_latitude - latitude of the weather location')
    print('             @weather_humidity - percetnage of humanity')
    print('             @weather_sunset - time of sunset')
    print('             @weather_sunrise - time of sunrise')
    print('             @weather_windspeed - speed of wind today')
    print('             @weather_cloudiness - percentage of cloudiness')
    print('             @weather_city - city name for weather')
    print('LastFM:')
    print('             @lastfm - top 5 artists of today')
    print('             @lastfm_top_5artists - top 5 artists of today')
    print('             @lastfm_top_5tracks - top 5 tracks of today')
    print('             @lastfm_top_5albums - top 5 albums of today')
    print('             @lastfm_top_5tags - top 5 tags of today')
    print('ExtraCreditAPI:')
    print('             @extracredit - a random quote')
    print('Q: quits the Program')

menu()
